### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by BigDeepBlue** [Pummas/graduate_work#12]
Привет! Хорошая работа. Вот небольшой список рекомендаций:

1. Можно лучше: максимально рекомендую [длинну](https://github.com/Pummas/graduate_work/blob/d282f0979ce2ddb63ebc460aa3092b1aa77be629/pyproject.toml#L2) строки ограничить в  79 или 88 символов. 120 - это слишком широкая строка. Такой размер влияет на удобство разработки - такая строка чаще всего не влезает в экраны при их разделении, плюс широкая строка дает просто для написания сложных выражений
2. Чтобы [дев-зависимости](https://github.com/Pummas/graduate_work/blob/d282f0979ce2ddb63ebc460aa3092b1aa77be629/cdn/sync_service/requirements.txt#L4) не растаскивать по отдельным кускам вашего репо можно [здесь](https://github.com/Pummas/graduate_work/blob/main/pyproject.toml) их все указать в отдельной группе https://python-poetry.org/docs/pyproject/#dependencies-and-dependency-groups - если вы используете poetry, либо просто создать `requirements.dev.txt` если у вас pip
3. А зачем [такая](https://github.com/Pummas/graduate_work/blob/main/cdn/sync_service/check.py) чекалка? Вы же используете BaseSettings, в них и сделайте проверку
4. [Тут](https://github.com/Pummas/graduate_work/blob/d282f0979ce2ddb63ebc460aa3092b1aa77be629/cdn/sync_service/app/api/v1/films.py#L29) вы нарушаете транзакционность, то есть вы можете вставить часть информации, а остальную после этой ошибки - нет. Это нормально для вашей архитектуру? Вы сможете повторно обработать событие?
5. А как вы понимаете, что не все фильмы отсинхронизовали с таким [break](https://github.com/Pummas/graduate_work/blob/d282f0979ce2ddb63ebc460aa3092b1aa77be629/cdn/sync_service/app/services/sync.py#L42)?
6. Давайте все [атрибуты](https://github.com/Pummas/graduate_work/blob/d282f0979ce2ddb63ebc460aa3092b1aa77be629/cdn/routing_service/src/settings.py#L13) в нижний регистр для единообразия
7. В [таких](https://github.com/Pummas/graduate_work/blob/d282f0979ce2ddb63ebc460aa3092b1aa77be629/cdn/routing_service/src/utils.py#L9) условия можно проще писать:
```python
if request.client.host == "127.0.0.1":
    return fake.ipv4()
return request.client.host
```
8. Можно лучше: [Воркера](https://github.com/Pummas/graduate_work/blob/d282f0979ce2ddb63ebc460aa3092b1aa77be629/cdn/routing_service/src/api/v1/media.py#L20) можно через Depends сделать
9. Вместо [числовых](https://github.com/Pummas/graduate_work/blob/d282f0979ce2ddb63ebc460aa3092b1aa77be629/cdn/routing_service/src/api/v1/media.py#L25) статус-кодов рекомендую использовать `http.HTTPStatus`
10. Можно лучше: [тут](https://github.com/Pummas/graduate_work/blob/d282f0979ce2ddb63ebc460aa3092b1aa77be629/cdn/load_service/src/workers/worker.py#L64) вы все равно синхронно в редис запихиваете задачу и вешаете ивентлуп. То есть celery нельзя просто взять и запихнуть в fastapi. Тут вам нужно либо делать синхронные роутеры под такие кейсы. Либо использовать что-то вроде https://github.com/mosquito/aio-pika и с другой стороны на очереди в отдельном приложении вешать celery

**Comment by s-morichev** [comment]
1. Ограничение в 80 символов пошло от перфокарт, там как раз было 80 столбиков, потом на экранах терминалов был текстовый режим 80х25 символов. Сейчас же экраны стали побольше, соотношение сторон в основном 16:9, строка 120 символов легко помещается. Это позволяет не экономить на длине названий переменных и давать им более осмысленные имена, при этом функция с параметрами помещается в одной строке. С командой решили, что 120 символов всех устраивает. Конечно, все зависит от принятых правил в каждом проекте.
2. Создали `requirements.dev.txt ` в корне репозитория и перенесли в него dev-зависимости
3. Лишний файл в коммит попал, удалили.
4. Добавили логирование. Если пришло событие от хранилища, которое не зарегистировано в базе, то что-то где-то сильно поломалось, например, случайно удалили запись о хранилище из базы. Тогда надо делать синхронизацию между базой данных и фактическим наличием файлов в хранилище, думали над такой возможностью, но не реализовали.
5. Синхронизируются не все фильмы. На edge сервера скачиваются более популярные фильмы, сколько поместится. Менее популярные раздаются с мастера.
6.
7.
8.
9.
10.  Эта функция вызывается из /tasks/sync, получает список задач на удаление и закачку, проходит по ним и пишет в редис задачи. Можно это делать и асинхронно, но есть ли смысл? Синхронизация будет вызываться ну пусть раз в час, сервис особо не нагружен. Все задачи даже в синхронной загрузке думаю за 1сек точно должны записаться в редис. А дальше уже воркер celery будет крутиться и выполнять удаления и загрузки.

**Comment by Pummas** [comment]
6. Поменял
7. Исправил
8. Поместил
9. Исправил

**Comment by BigDeepBlue** [comment]
> Ограничение в 80 символов пошло от перфокарт, там как раз было 80 столбиков, потом на экранах терминалов был текстовый режим 80х25 символов. Сейчас же экраны стали побольше, соотношение сторон в основном 16:9, строка 120 символов легко помещается. Это позволяет не экономить на длине названий переменных и давать им более осмысленные имена, при этом функция с параметрами помещается в одной строке. С командой решили, что 120 символов всех устраивает. Конечно, все зависит от принятых правил в каждом проекте.

Да, все так, поэтому и можно лучше) Но во многих командах используются длинну меньше 100 и это явно не из-за работы с перфокартами, а из-за моего второго аргумента - длинная строка дает больше простора для написания сложного кода

> Эта функция вызывается из /tasks/sync, получает список задач на удаление и закачку, проходит по ним и пишет в редис задачи

Это тоже было под "можно лучше" то есть в вашем кейсе и с учетом MVP - ок, но в целом имейте ввиду на будущее, что в асинк просто так celery не затащить

Остальные правки посмотрел - все ок. Работу принимаю. Удачи на защите :rocket:
